name: Test with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker image
      run: docker pull kaikymoura/prjsps-imagem:latest

    - name: Run container
      run: |
        docker run -d --name SecurityVault -p 8089:8089 kaikymoura/prjsps-imagem:latest

    - name: Wait for container to be ready
      run: |
        sleep 30

    - name: Clean up
      run: |
        docker stop my-container
        docker rm my-container
